## Author: Tito Valentin
## Name of Program: resolveRepackage Gitleaks Configuration
## Date Created: 2026-07-13
## Description: Extends the default Gitleaks rules for repository history scans.
title = "resolveRepackage gitleaks configuration"

[extend]
useDefault = true
